


# for testing
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tinfo370Testing
    username: postgres
    password: Qwdf3696!


#for deploying
#spring:
#  datasource:
#    url: jdbc:postgresql://ec2-3-234-204-26.compute-1.amazonaws.com/ddna60m4ep296u
#    username: rrjkahwvajyymo
#    password: 6243eb68ab0c993c0897d5ad5f94a10087a644f93716fec8be116d30c4191541

#  profiles:
#    include: oauth

  #db detail setting


  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 270190684241-lkvd3tcn12dfr93e1i0gobk9otidu443.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
server:
  port: ${PORT:8080}


logging:
  level:
    org:
      hibernate:
        sql: DEBUG
